/* =====================================================
   ESTRUTURA DE DADOS COMPLETA - GERAÇÃO TECH 2026
   Revisão: Verificação de datas Seg/Qua vs Ter/Qui
===================================================== */

window.cronogramas = {
  /* ---------------------------------------------------
     IA GENERATIVA (IA_GEN)
  --------------------------------------------------- */
  ia_gen: {
    // Turma: Terça e Quinta
    terqui: [
      { aula: 1, data: "13/01/2026 - Terça", modulo: "Módulo 01", tema: "Introdução à IA Generativa e LLMs", roadmap: "Exploração dos fundamentos da IA Generativa, arquiteturas Transformer e etapas de pré-treinamento.", atividade: "Práticas em LLMs tradicionais e leitura de artigo sugerido.", objetivo: "Compreender o funcionamento de LLMs e arquiteturas modernas.", sugestoes: ["Modelos de Linguagem", "Transformer"], sites: "huggingface.co/learn" },
      { aula: 2, data: "15/01/2026 - Quinta", modulo: "Módulo 01", tema: "Ética, Segurança e Impacto Ambiental", roadmap: "Análise de vieses, privacidade, uso indevido e consumo energético.", atividade: "Discussão sobre Model Cards e pegada de carbono.", objetivo: "Avaliar riscos e marcos éticos.", sugestoes: ["Vieses", "AI Act"], sites: "incidentdatabase.ai" },
      { aula: 3, data: "20/01/2026 - Terça", modulo: "Módulo 01", tema: "Engenharia de Prompt – fundamentos", roadmap: "Técnicas de Zero-shot, Few-shot e estrutura de instruções.", atividade: "Aplicação prática de prompts em grupo.", objetivo: "Dominar técnicas para maximizar precisão.", sugestoes: ["Zero-shot", "Few-shot"], sites: "promptingguide.ai" },
      { aula: 4, data: "22/01/2026 - Quinta", modulo: "Módulo 01", tema: "Engenharia de Prompt – boas práticas", roadmap: "Refinamento de prompts complexos e estratégias avançadas.", atividade: "Laboratório prático de prompts dirigidos.", objetivo: "Reduzir alucinações via contexto.", sugestoes: ["Iteração", "Delimitadores"], sites: "platform.openai.com/docs" },
      { aula: 5, data: "27/01/2026 - Terça", modulo: "Módulo 01", tema: "Exploração de APIs de LLMs", roadmap: "Comunicação RESTful, autenticação e parâmetros técnicos.", atividade: "Acessar LLM via API (Gemini).", objetivo: "Integrar modelos via programação.", sugestoes: ["API Keys", "Tokens"], sites: "google.dev/gemini" },
      { aula: 6, data: "29/01/2026 - Quinta", modulo: "Módulo 01", tema: "Prática com APIs de IA", roadmap: "Tratamento de retorno das respostas e análise de custo.", atividade: "Criação de script para chamada de API simples.", objetivo: "Gerenciar fluxos de dados via código.", sugestoes: ["JSON", "Requests"], sites: "docs.n8n.io" },
      { aula: 7, data: "03/02/2026 - Terça", modulo: "Módulo 02", tema: "Vetorização e Embeddings", roadmap: "Fundamentos de vetorização e embeddings semânticos.", atividade: "Exercícios com Pinecone e FAISS.", objetivo: "Entender representação vetorial.", sugestoes: ["TF-IDF", "BERT"], sites: "pinecone.io" },
      { aula: 8, data: "05/02/2026 - Quinta", modulo: "Módulo 02", tema: "Embeddings na prática", roadmap: "Indexação e busca por similaridade.", atividade: "Criação de base vetorial simples.", objetivo: "Aplicar busca semântica.", sugestoes: ["Chroma", "Vectores"], sites: "" },
      { aula: 9, data: "10/02/2026 - Terça", modulo: "Módulo 02", tema: "Recuperação de Contexto (RAG)", roadmap: "Arquitetura RAG: Indexação, Consulta e Geração.", atividade: "Pipeline básico de RAG com documentos.", objetivo: "Implementar recuperação baseada em contexto.", sugestoes: ["LlamaIndex", "Search"], sites: "" },
      { aula: 10, data: "12/02/2026 - Quinta", modulo: "Módulo 02", tema: "Estratégias de Recuperação", roadmap: "Ranking, filtros e otimização de busca.", atividade: "Refinamento de consulta RAG.", objetivo: "Melhorar precisão da recuperação.", sugestoes: ["Ranking", "LangChain"], sites: "" },
      { aula: 11, data: "17/02/2026 - Terça", modulo: "Módulo 02", tema: "Aplicações de RAG e Avaliação", roadmap: "Métricas de avaliação (Recall, Precisão) e custos.", atividade: "Teste de performance em pipeline RAG.", objetivo: "Avaliar qualidade das respostas geradas.", sugestoes: ["Métricas RAGAS", "Custo"], sites: "" },
      { aula: 12, data: "19/02/2026 - Quinta", modulo: "Módulo 02", tema: "Model Context Protocol (MCP)", roadmap: "Estudo do padrão MCP para contexto estruturado.", atividade: "Configuração de contexto via MCP.", objetivo: "Padronizar fornecimento de dados para LLMs.", sugestoes: ["Padrão MCP", "Copilotos"], sites: "modelcontextprotocol.io" },
      { aula: 13, data: "24/02/2026 - Terça", modulo: "Módulo 03", tema: "Automação Low-code", roadmap: "Introdução ao n8n e plataformas visuais.", atividade: "Criação de fluxo de notificação automático.", objetivo: "Automatizar processos sem código complexo.", sugestoes: ["n8n", "Zapier"], sites: "docs.n8n.io" },
      { aula: 14, data: "26/02/2026 - Quinta", modulo: "Módulo 03", tema: "Integrações Práticas", roadmap: "Webhooks e integrações com Notion/Sheets.", atividade: "Conectar formulário à API de IA via n8n.", objetivo: "Sincronizar dados entre plataformas.", sugestoes: ["Webhooks", "Notion"], sites: "" },
      { aula: 15, data: "03/03/2026 - Terça", modulo: "Módulo 03", tema: "Data Lake e Organização", roadmap: "Estratégias de armazenamento e governança de dados.", atividade: "Estruturação de repositório no AWS S3.", objetivo: "Organizar dados para consumo de IA.", sugestoes: ["AWS S3", "Delta Lake"], sites: "docs.delta.io" },
      { aula: 16, data: "05/03/2026 - Quinta", modulo: "Módulo 03", tema: "Data Pipelines (ETL)", roadmap: "Transformação de dados com dbt e Airbyte.", atividade: "Construção de pipeline de ingestão.", objetivo: "Escalar fluxos de dados para GenAI.", sugestoes: ["dbt", "Airbyte"], sites: "" },
      { aula: 17, data: "10/03/2026 - Terça", modulo: "Módulo 03", tema: "Workflows Complexos", roadmap: "Tratamento de erros e logs em automações.", atividade: "Debug de fluxo no n8n.", objetivo: "Garantir robustez em processos automatizados.", sugestoes: ["JSON Parse", "Logs"], sites: "" },
      { aula: 18, data: "12/03/2026 - Quinta", modulo: "Módulo 03", tema: "Data Lake Aplicado", roadmap: "Casos reais de uso de Data Lakes em projetos de IA.", atividade: "Workshop prático de consulta em Lake.", objetivo: "Extrair valor de grandes volumes de dados.", sugestoes: ["Casos Reais", "Governança"], sites: "" },
      { aula: 19, data: "17/03/2026 - Terça", modulo: "Módulo 04", tema: "Agentes Autônomos", roadmap: "Introdução ao LangGraph e CrewAI.", atividade: "Definição de papéis (roles) para agentes.", objetivo: "Criar fluxos de raciocínio encadeado.", sugestoes: ["LangGraph", "CrewAI"], sites: "" },
      { aula: 20, data: "19/03/2026 - Quinta", modulo: "Módulo 04", tema: "Segurança e Responsabilidade", roadmap: "Proteção contra Prompt Injection e Guardrails.", atividade: "Teste de vulnerabilidades em agentes.", objetivo: "Proteger aplicações contra entradas maliciosas.", sugestoes: ["Guardrails", "Vulnerabilidades"], sites: "" },
      { aula: 21, data: "24/03/2026 - Terça", modulo: "Módulo 04", tema: "Construção de Agentes Inteligentes", roadmap: "Roteamento de tarefas e orquestração de ferramentas.", atividade: "Criação de agente com acesso a banco de dados.", objetivo: "Desenvolver sistemas que tomam decisões autônomas.", sugestoes: ["Orquestração", "Semantic Router"], sites: "" },
      { aula: 22, data: "26/03/2026 - Quinta", modulo: "Módulo 04", tema: "Agentes na Prática", roadmap: "Aprimoramento de performance e depuração de agentes.", atividade: "Hands-on: Refinando o raciocínio do agente.", objetivo: "Otimizar a execução de planos complexos.", sugestoes: ["Debug", "Aprimoramentos"], sites: "" },
      { aula: 23, data: "31/03/2026 - Terça", modulo: "Módulo 04", tema: "Integrações com Bancos de Dados", roadmap: "Persistência de memória em Supabase e Redis.", atividade: "Configurar memória persistente para chatbot.", objetivo: "Manter contexto em conversas longas.", sugestoes: ["Supabase", "Redis"], sites: "supabase.com" },
      { aula: 24, data: "02/04/2026 - Quinta", modulo: "Módulo 04", tema: "Encerramento e Consolidação", roadmap: "Revisão geral do curso e feedback final.", atividade: "Apresentação de mini-projeto consolidado.", objetivo: "Consolidar o aprendizado total da formação.", sugestoes: ["Revisão", "Feedback"], sites: "" }
    ],

    // Turma: Segunda e Quarta (REVISADO DIA A DIA)
    segqua: [
      { aula: 1, data: "14/01/2026 - Quarta", modulo: "Módulo 01", tema: "Introdução à IA Generativa e LLMs", roadmap: "Exploração dos fundamentos da IA Generativa, arquiteturas Transformer.", atividade: "Práticas em LLMs tradicionais e leitura de artigo.", objetivo: "Compreender o funcionamento de LLMs.", sugestoes: ["Modelos", "Transformer"], sites: "" },
      { aula: 2, data: "19/01/2026 - Segunda", modulo: "Módulo 01", tema: "Ética, Segurança e Impacto Ambiental", roadmap: "Vieses, privacidade e consumo energético.", atividade: "Discussão sobre pegada de carbono.", objetivo: "Avaliar riscos éticos.", sugestoes: ["Vieses", "AI Act"], sites: "" },
      { aula: 3, data: "21/01/2026 - Quarta", modulo: "Módulo 01", tema: "Engenharia de Prompt – fundamentos", roadmap: "Técnicas de Zero-shot, Few-shot e estrutura.", atividade: "Prática de prompts em grupo.", objetivo: "Dominar instruções eficazes.", sugestoes: ["Prompting"], sites: "" },
      { aula: 4, data: "26/01/2026 - Segunda", modulo: "Módulo 01", tema: "Engenharia de Prompt – boas práticas", roadmap: "Refinamento e estratégias avançadas.", atividade: "Laboratório de prompts dirigidos.", objetivo: "Reduzir alucinações.", sugestoes: ["Iteração"], sites: "" },
      { aula: 5, data: "28/01/2026 - Quarta", modulo: "Módulo 01", tema: "Exploração de APIs de LLMs", roadmap: "Comunicação RESTful, API Keys.", atividade: "Acessar LLM via API (Gemini).", objetivo: "Integrar via programação.", sugestoes: ["Tokens"], sites: "" },
      { aula: 6, data: "02/02/2026 - Segunda", modulo: "Módulo 01", tema: "Prática com APIs de IA", roadmap: "Tratamento de retorno e análise de custo.", atividade: "Script de chamada simples.", objetivo: "Gerenciar fluxos de dados.", sugestoes: ["JSON"], sites: "" },
      { aula: 7, data: "04/02/2026 - Quarta", modulo: "Módulo 02", tema: "Vetorização e Embeddings", roadmap: "Representação vetorial semântica.", atividade: "Exercícios com Pinecone.", objetivo: "Entender embeddings.", sugestoes: ["Embeddings"], sites: "" },
      { aula: 8, data: "09/02/2026 - Segunda", modulo: "Módulo 02", tema: "Embeddings na prática", roadmap: "Indexação e busca.", atividade: "Criação de base vetorial.", objetivo: "Aplicar busca semântica.", sugestoes: ["Chroma"], sites: "" },
      { aula: 9, data: "11/02/2026 - Quarta", modulo: "Módulo 02", tema: "Recuperação de Contexto (RAG)", roadmap: "Arquitetura RAG básica.", atividade: "Pipeline de documentos.", objetivo: "Implementar RAG.", sugestoes: ["LlamaIndex"], sites: "" },
      { aula: 10, data: "16/02/2026 - Segunda", modulo: "Módulo 02", tema: "Estratégias de Recuperação", roadmap: "Ranking e filtros.", atividade: "Refinamento RAG.", objetivo: "Melhorar precisão.", sugestoes: ["LangChain"], sites: "" },
      { aula: 11, data: "18/02/2026 - Quarta", modulo: "Módulo 02", tema: "Aplicações de RAG e Avaliação", roadmap: "Métricas de avaliação.", atividade: "Teste de performance.", objetivo: "Avaliar qualidade.", sugestoes: ["Métricas"], sites: "" },
      { aula: 12, data: "23/02/2026 - Segunda", modulo: "Módulo 02", tema: "Model Context Protocol (MCP)", roadmap: "Padrão MCP estruturado.", atividade: "Configuração via MCP.", objetivo: "Padronizar contexto.", sugestoes: ["MCP"], sites: "" },
      { aula: 13, data: "25/02/2026 - Quarta", modulo: "Módulo 03", tema: "Automação Low-code", roadmap: "n8n e automação visual.", atividade: "Fluxo de notificação.", objetivo: "Automatizar processos.", sugestoes: ["n8n"], sites: "" },
      { aula: 14, data: "02/03/2026 - Segunda", modulo: "Módulo 03", tema: "Integrações Práticas", roadmap: "Webhooks e Notion.", atividade: "Formulário + API via n8n.", objetivo: "Sincronizar plataformas.", sugestoes: ["Webhooks"], sites: "" },
      { aula: 15, data: "04/03/2026 - Quarta", modulo: "Módulo 03", tema: "Data Lake e Organização", roadmap: "Governança e AWS S3.", atividade: "Repositório S3.", objetivo: "Organizar dados.", sugestoes: ["AWS S3"], sites: "" },
      { aula: 16, data: "09/03/2026 - Segunda", modulo: "Módulo 03", tema: "Data Pipelines (ETL)", roadmap: "dbt e Airbyte.", atividade: "Ingestão de dados.", objetivo: "Escalar fluxos.", sugestoes: ["ETL"], sites: "" },
      { aula: 17, data: "11/03/2026 - Quarta", modulo: "Módulo 03", tema: "Workflows Complexos", roadmap: "Erros e logs.", atividade: "Debug n8n.", objetivo: "Garantir robustez.", sugestoes: ["Debug"], sites: "" },
      { aula: 18, data: "16/03/2026 - Segunda", modulo: "Módulo 03", tema: "Data Lake Aplicado", roadmap: "Casos reais.", atividade: "Workshop de consulta.", objetivo: "Extrair valor.", sugestoes: ["Casos Reais"], sites: "" },
      { aula: 19, data: "18/03/2026 - Quarta", modulo: "Módulo 04", tema: "Agentes Autônomos", roadmap: "LangGraph e CrewAI.", atividade: "Definição de papéis.", objetivo: "Raciocínio encadeado.", sugestoes: ["Agentes"], sites: "" },
      { aula: 20, data: "23/03/2026 - Segunda", modulo: "Módulo 04", tema: "Segurança e Responsabilidade", roadmap: "Prompt Injection.", atividade: "Teste de vulnerabilidade.", objetivo: "Proteger aplicações.", sugestoes: ["Segurança"], sites: "" },
      { aula: 21, data: "25/03/2026 - Quarta", modulo: "Módulo 04", tema: "Construção de Agentes Inteligentes", roadmap: "Orquestração de ferramentas.", atividade: "Agente + Banco de dados.", objetivo: "Decisões autônomas.", sugestoes: ["Orquestração"], sites: "" },
      { aula: 22, data: "30/03/2026 - Segunda", modulo: "Módulo 04", tema: "Agentes na Prática", roadmap: "Otimização de performance.", atividade: "Hands-on: Refinando plano.", objetivo: "Execução complexa.", sugestoes: ["Hands-on"], sites: "" },
      { aula: 23, data: "01/04/2026 - Quarta", modulo: "Módulo 04", tema: "Integrações com Bancos de Dados", roadmap: "Supabase e Redis.", atividade: "Chatbot persistente.", objetivo: "Contexto longo.", sugestoes: ["Persistência"], sites: "" },
      { aula: 24, data: "06/04/2026 - Segunda", modulo: "Módulo 04", tema: "Encerramento e Consolidação", roadmap: "Revisão e feedback.", atividade: "Mini-projeto final.", objetivo: "Consolidar aprendizado.", sugestoes: ["Conclusão"], sites: "" }
    ]
  },

 /* ---------------------------------------------------
      IASP – IA + SOFT SKILLS PARA PROGRAMADORES
  --------------------------------------------------- */
  iasp: {
    /* -------- TERÇA E QUINTA -------- */
    terqui: [
      { aula: 1, data: "13/01/2026 - Terça", modulo: "Módulo 01", tema: "Panorama histórico e evolução da IA", roadmap: "1. O que é IA? 2. Linha do tempo (anos 50-hoje). 3. Invernos/Verões. 4. De Sistemas Especialistas a ML. 5. Transformers.", atividade: "Linha do Tempo Interativa: Criar infográfico com 5 marcos revolucionários.", objetivo: "Compreender trajetória histórica.", sugestoes: ["História", "Marcos"], sites: "huggingface.co" },
      { aula: 2, data: "15/01/2026 - Quinta", modulo: "Módulo 01", tema: "Tipos de IA e Trabalho Técnico", roadmap: "1. IA Fraca vs Forte. 2. ML vs Deep Learning. 3. Redes Neurais. 4. CNNs e Transformers.", atividade: "Análise: Explicar qual IA ferramentas como Copilot utilizam.", objetivo: "Diferenciar subcampos.", sugestoes: ["ANI x AGI", "ML x DL"], sites: "" },
      { aula: 3, data: "20/01/2026 - Terça", modulo: "Módulo 01", tema: "Ética e uso responsável da IA", roadmap: "1. Natureza probabilística. 2. Viés em datasets. 3. Privacidade e LGPD. 4. Transparência.", atividade: "Debate Ético: Dilemas em contratações.", objetivo: "Analisar implicações éticas.", sugestoes: ["Alucinações", "Viés"], sites: "lgpd-brasil.info" },
      { aula: 4, data: "22/01/2026 - Quinta", modulo: "Módulo 01", tema: "IA Generativa e o futuro do dev", roadmap: "1. Modelos generativos. 2. Prompt Engineering. 3. Boilerplates e Refatoração. 4. Vibe Coding.", atividade: "Pair Programming: Refatorar código com GenAI.", objetivo: "Otimizar tarefas de dev.", sugestoes: ["Prompting", "Vibe Coding"], sites: "" },
      { aula: 5, data: "27/01/2026 - Terça", modulo: "Módulo 01", tema: "Profissões em transformação", roadmap: "1. Impacto e automação. 2. Novas carreiras. 3. Dev Centauro. 4. Lifelong Learning.", atividade: "Revisão de Vaga: Atualizar vaga de 2020 para 2026.", objetivo: "Identificar novas habilidades.", sugestoes: ["Carreiras", "Soft Skills"], sites: "" },
      { aula: 6, data: "29/01/2026 - Quinta", modulo: "Módulo 02", tema: "Assistentes de código", roadmap: "1. Copilot, Cursor, Windsurf. 2. Configuração. 3. Geração via linguagem natural.", atividade: "Gerador de Funções: Criar validação de CPF apenas via comentários.", objetivo: "Configurar assistentes.", sugestoes: ["Copilot", "Cursor"], sites: "" },
      { aula: 7, data: "03/02/2026 - Terça", modulo: "Módulo 02", tema: "Explicação e refatoração de código por IA", roadmap: "1. Código legado. 2. IA como tradutor. 3. Refatoração assistida (performance e Clean Code).", atividade: "Refatorando o Legado: IA explica e melhora código complexo.", objetivo: "Interpretar e melhorar código legado.", sugestoes: ["Refatoração", "Patterns"], sites: "" },
      { aula: 8, data: "05/02/2026 - Quinta", modulo: "Módulo 02", tema: "Documentação técnica automatizada", roadmap: "1. Docstrings. 2. README.md. 3. Documentação de API.", atividade: "Documentador Instantâneo: Gerar documentação para repositório vazio.", objetivo: "Automatizar a consistência documental.", sugestoes: ["README", "Docstrings"], sites: "" },
      { aula: 9, data: "10/02/2026 - Terça", modulo: "Módulo 02", tema: "Criação de testes com apoio de IA", roadmap: "1. Testes unitários. 2. Edge cases. 3. Mock Data.", atividade: "Caçador de Bugs: Gerar testes de borda e mocks.", objetivo: "Aumentar cobertura e qualidade.", sugestoes: ["Unit Test", "Mocks"], sites: "" },
      { aula: 10, data: "12/02/2026 - Quinta", modulo: "Módulo 02", tema: "Debug com apoio de IA", roadmap: "1. Stack Traces. 2. Análise de Logs. 3. Correção em tempo real.", atividade: "O Detetive: Submeter erro real à IA para causa raiz e fix.", objetivo: "Acelerar o ciclo de depuração.", sugestoes: ["Debug", "Logs"], sites: "" },
      { aula: 11, data: "17/02/2026 - Terça", modulo: "Módulo 02", tema: "Automatização de tarefas e scripts", roadmap: "1. Shell/Python. 2. Dockerfile. 3. CI/CD.", atividade: "O DevOps Assistente: Scripts e Docker via IA.", objetivo: "Reduzir trabalho manual operacional.", sugestoes: ["DevOps", "Scripts"], sites: "" },
      { aula: 12, data: "19/02/2026 - Quinta", modulo: "Módulo 02", tema: "Prática integrada com ferramentas", roadmap: "Workshop prático integrando os conhecimentos do Módulo 2.", atividade: "Hands-on: Desenvolver mini-projeto assistido.", objetivo: "Consolidar o domínio das ferramentas.", sugestoes: ["Hands-on"], sites: "" },
      { aula: 13, data: "24/02/2026 - Terça", modulo: "Módulo 02", tema: "Consolidação do módulo", roadmap: "Revisão técnica e feedbacks do Módulo 2.", atividade: "Apresentação de tarefa automatizada individual.", objetivo: "Garantir absorção técnica.", sugestoes: ["Revisão"], sites: "" },
      { aula: 14, data: "26/02/2026 - Quinta", modulo: "Módulo 03", tema: "LLMs e Engenharia de Prompt", roadmap: "1. Tokens. 2. APIs Comerciais vs Locais. 3. Técnicas de Prompting.", atividade: "Batalha de Prompts: Avaliar 3 estratégias de instrução.", objetivo: "Dominar a interface com LLMs.", sugestoes: ["Ollama", "Prompting"], sites: "" },
      { aula: 15, data: "03/03/2026 - Terça", modulo: "Módulo 03", tema: "Consumo de APIs de IA", roadmap: "1. Ambiente. 2. Chaves e Env Vars. 3. Chamadas HTTP. 4. JSON Estruturado.", atividade: "Script: Classificador de sentimento de reviews.", objetivo: "Integrar APIs via código.", sugestoes: ["Axios", "Requests"], sites: "" },
      { aula: 16, data: "05/03/2026 - Quinta", modulo: "Módulo 03", tema: "Criação de assistentes personalizados", roadmap: "1. Frameworks (LangChain). 2. Conceito de RAG. 3. Conhecimento externo.", atividade: "Meu Primeiro RAG: Assistente baseado em PDF/TXT local.", objetivo: "Conectar IA a dados privados.", sugestoes: ["LangChain", "RAG"], sites: "" },
      { aula: 17, data: "10/03/2026 - Terça", modulo: "Módulo 03", tema: "Automação com n8n", roadmap: "1. n8n. 2. Triggers/Actions. 3. Workflows visuais.", atividade: "Workflow n8n: Extrair dados de e-mail para Sheets via IA.", objetivo: "Criar automações complexas sem código.", sugestoes: ["n8n", "No-code"], sites: "" },
      { aula: 18, data: "12/03/2026 - Quinta", modulo: "Módulo 04", tema: "Comunicação técnica e não técnica", roadmap: "1. IA como apoio na escrita. 2. Tradução de jargão para negócios.", atividade: "Refinar e-mails e relatórios técnicos com IA.", objetivo: "Melhorar a clareza interpessoal.", sugestoes: ["Soft Skills", "E-mail"], sites: "" },
      { aula: 19, data: "17/03/2026 - Terça", modulo: "Módulo 04", tema: "Trabalho em equipe e liderança", roadmap: "1. Colaboração assertiva. 2. Liderança proativa.", atividade: "Feedback Construtivo: Simular reuniões de equipe via IA.", objetivo: "Desenvolver sinergia e liderança.", sugestoes: ["Feedback", "Times"], sites: "" },
      { aula: 20, data: "19/03/2026 - Quinta", modulo: "Módulo 04", tema: "Inteligência emocional e resiliência", roadmap: "1. Autoconhecimento. 2. Pressão em TI. 3. Mentalidade construtiva.", atividade: "Simulação de Crise: Lidando com falhas críticas via IA Coach.", objetivo: "Manter performance sob pressão.", sugestoes: ["IE", "Resiliência"], sites: "" },
      { aula: 21, data: "24/03/2026 - Terça", modulo: "Módulo 04", tema: "Gestão do tempo e pensamento crítico", roadmap: "1. Matriz de Eisenhower. 2. Priorização com IA. 3. Validação de saídas de IA.", atividade: "Planejador de Foco: IA para otimizar o calendário semanal.", objetivo: "Aumentar produtividade e criticidade.", sugestoes: ["Foco", "Eisenhower"], sites: "" },
      { aula: 22, data: "26/03/2026 - Quinta", modulo: "Módulo 05", tema: "Definição do problema", roadmap: "1. Ideação. 2. MVP. 3. Viabilidade. 4. Pitch.", atividade: "Pitch do Projeto: Definir problema e escopo.", objetivo: "Articular soluções de IA.", sugestoes: ["MVP", "Ideação"], sites: "draw.io" },
      { aula: 23, data: "31/03/2026 - Terça", modulo: "Módulo 05", tema: "Desenvolvimento do projeto", roadmap: "Implementação técnica do MVP acompanhada por mentoria.", atividade: "Hackathon: Codificação do fluxo Entrada -> IA -> Saída.", objetivo: "Implementar a solução planejada.", sugestoes: ["Coding", "Lab"], sites: "" },
      { aula: 24, data: "02/04/2026 - Quinta", modulo: "Módulo 05", tema: "Apresentação e feedback", roadmap: "1. Storytelling. 2. Demo Day. 3. Avaliação final.", atividade: "Pitch Final: Demonstração e defesa da solução.", objetivo: "Comunicar valor e resultados.", sugestoes: ["Storytelling", "Pitch"], sites: "" }
    ],

    /* -------- SEGUNDA E QUARTA -------- */
    segqua: [
      { aula: 1, data: "14/01/2026 - Quarta", modulo: "Módulo 01", tema: "Panorama histórico e evolução da IA", roadmap: "Trajetória da IA dos anos 50 até hoje.", atividade: "Linha do tempo.", objetivo: "Compreender história.", sugestoes: ["História"], sites: "" },
      { aula: 2, data: "19/01/2026 - Segunda", modulo: "Módulo 01", tema: "Tipos de IA e Trabalho Técnico", roadmap: "IA Fraca vs Forte, ML vs DL.", atividade: "Análise Copilot.", objetivo: "Diferenciar campos.", sugestoes: ["ANI x AGI"], sites: "" },
      { aula: 3, data: "21/01/2026 - Quarta", modulo: "Módulo 01", tema: "Ética e uso responsável da IA", roadmap: "Vieses, privacidade e LGPD.", atividade: "Debate Ético.", objetivo: "Análise crítica.", sugestoes: ["Ética"], sites: "" },
      { aula: 4, data: "26/01/2026 - Segunda", modulo: "Módulo 01", tema: "IA Generativa e o futuro do dev", roadmap: "Modelos generativos e Engenharia de Prompt.", atividade: "Refatoração com IA.", objetivo: "Otimizar dev.", sugestoes: ["GenAI"], sites: "" },
      { aula: 5, data: "28/01/2026 - Quarta", modulo: "Módulo 01", tema: "Profissões em transformação", roadmap: "Impacto no mercado e Dev Centauro.", atividade: "Revisão de vaga.", objetivo: "Novas carreiras.", sugestoes: ["Lifelong Learning"], sites: "" },
      { aula: 6, data: "02/02/2026 - Segunda", modulo: "Módulo 02", tema: "Assistentes de código", roadmap: "Copilot, Cursor e configuração IDE.", atividade: "Gerador de funções.", objetivo: "Usar assistentes.", sugestoes: ["Cursor"], sites: "" },
      { aula: 7, data: "04/02/2026 - Quarta", modulo: "Módulo 02", tema: "Explicação e refatoração de código", roadmap: "Código legado e tradução técnica.", atividade: "Refatoração na prática.", objetivo: "Melhorar legibilidade.", sugestoes: ["Clean Code"], sites: "" },
      { aula: 8, data: "09/02/2026 - Segunda", modulo: "Módulo 02", tema: "Documentação técnica automatizada", roadmap: "READMEs e documentação de API via IA.", atividade: "Documentador Instantâneo.", objetivo: "Automatizar docs.", sugestoes: ["README"], sites: "" },
      { aula: 9, data: "11/02/2026 - Quarta", modulo: "Módulo 02", tema: "Criação de testes com apoio de IA", roadmap: "Testes unitários e mocks.", atividade: "Caçador de bugs.", objetivo: "Qualidade de software.", sugestoes: ["Testes"], sites: "" },
      { aula: 10, data: "16/02/2026 - Segunda", modulo: "Módulo 02", tema: "Debug com apoio de IA", roadmap: "Logs e Stack Traces.", atividade: "Análise de erro real.", objetivo: "Debugging ágil.", sugestoes: ["Logs"], sites: "" },
      { aula: 11, data: "18/02/2026 - Quarta", modulo: "Módulo 02", tema: "Automatização de tarefas e scripts", roadmap: "Scripts Python/Shell via IA.", atividade: "DevOps assistente.", objetivo: "Automação operacional.", sugestoes: ["Docker"], sites: "" },
      { aula: 12, data: "23/02/2026 - Segunda", modulo: "Módulo 02", tema: "Prática integrada", roadmap: "Mini-projeto consolidando o Módulo 2.", atividade: "Hands-on integral.", objetivo: "Consolidação técnica.", sugestoes: ["Hands-on"], sites: "" },
      { aula: 13, data: "25/02/2026 - Quarta", modulo: "Módulo 02", tema: "Consolidação do módulo", roadmap: "Fechamento técnico e dúvidas.", atividade: "Apresentação técnica.", objetivo: "Avaliação contínua.", sugestoes: ["Feedback"], sites: "" },
      { aula: 14, data: "02/03/2026 - Segunda", modulo: "Módulo 03", tema: "LLMs e Engenharia de Prompt", roadmap: "Fundamentos de LLMs e tokens.", atividade: "Batalha de Prompts.", objetivo: "Engenharia de Prompt.", sugestoes: ["LLM"], sites: "" },
      { aula: 15, data: "04/03/2026 - Quarta", modulo: "Módulo 03", tema: "Consumo de APIs de IA", roadmap: "Chamadas HTTP e JSON.", atividade: "Classificador de Sentimento.", objetivo: "APIs na prática.", sugestoes: ["API"], sites: "" },
      { aula: 16, data: "09/03/2026 - Segunda", modulo: "Módulo 03", tema: "Criação de assistentes personalizados", roadmap: "Fundamentos de RAG e contexto.", atividade: "Meu Primeiro RAG.", objetivo: "RAG local.", sugestoes: ["RAG"], sites: "" },
      { aula: 17, data: "11/03/2026 - Quarta", modulo: "Módulo 03", tema: "Orquestração No-Code", roadmap: "n8n e automação visual.", atividade: "Workflow de feedback.", objetivo: "Criar automações.", sugestoes: ["n8n"], sites: "" },
      { aula: 18, data: "16/03/2026 - Segunda", modulo: "Módulo 03", tema: "Projeto: Microserviço", roadmap: "FastAPI/Express e Endpoints.", atividade: "API de sumarização.", objetivo: "Consolidar microserviços.", sugestoes: ["API"], sites: "" },
      { aula: 19, data: "18/03/2026 - Quarta", modulo: "Módulo 04", tema: "Comunicação Técnica", roadmap: "IA como apoio na escrita.", atividade: "Refinar e-mails com IA.", objetivo: "Melhorar clareza.", sugestoes: ["Comunicação"], sites: "" },
      { aula: 20, data: "23/03/2026 - Segunda", modulo: "Módulo 04", tema: "Trabalho em Equipe e Colaboração", roadmap: "Feedback e resolução de conflitos.", atividade: "Simulação de feedback.", objetivo: "Habilidades sociais.", sugestoes: ["Colaboração"], sites: "" },
      { aula: 21, data: "25/03/2026 - Quarta", modulo: "Módulo 04", tema: "Gestão do tempo com IA", roadmap: "Eisenhower e automação de agenda.", atividade: "Planejador de foco.", objetivo: "Produtividade.", sugestoes: ["Tempo"], sites: "" },
      { aula: 22, data: "30/03/2026 - Segunda", modulo: "Módulo 05", tema: "Definição do problema", roadmap: "Ideação e MVP.", atividade: "Pitch do projeto.", objetivo: "Escopo de projeto.", sugestoes: ["Projeto"], sites: "" },
      { aula: 23, data: "01/04/2026 - Quarta", modulo: "Módulo 05", tema: "Desenvolvimento do projeto", roadmap: "Implementação assistida.", atividade: "Lab Hackathon.", objetivo: "Codificação IA.", sugestoes: ["Lab"], sites: "" },
      { aula: 24, data: "06/04/2026 - Segunda", modulo: "Módulo 05", tema: "Apresentação e feedback", roadmap: "Demo Day final.", atividade: "Pitch Final.", objetivo: "Resultados.", sugestoes: ["Encerramento"], sites: "" }
    ]
  }
};